version: '3'

volumes:
  hipsterate-flask-python-site-packages: {}
  hipsterate-flask-python-bin: {}

services:
  flask:
    container_name: hipsterate-flask
    build:
      context: .
      dockerfile: Dockerfile-flask
    command: /app/run-flask.sh
    ports:
      - 5001:5000
    volumes:
      - ./:/app
      - hipsterate-flask-python-site-packages:/venv/lib/python3.7/site-packages
      - hipsterate-flask-python-bin:/venv/bin
    environment:
      - FLASK_APP=app:app
      - FLASK_ENV=development
      - ENVIRONMENT=local
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_DEFAULT_REGION
    links:
      - mysql:mysql
    depends_on:
      - mysql
    stdin_open: true
    tty: true

  mysql:
    container_name: hipsterate-mysql
    image: mysql:5.6
    command: --character-set-server=utf8
    volumes:
      - ./mysql:/var/lib/mysql
    ports:
      - 43306:3306
    environment:
      - MYSQL_DATABASE=hipsterate
      - MYSQL_USER=local
      - MYSQL_PASSWORD=local
      - MYSQL_ROOT_PASSWORD=local
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 3s
      timeout: 3s
      retries: 10
