FROM python:3.7

ENV PYTHONUNBUFFERED=1
ENV PATH=/venv/bin:${PATH}

RUN pip install --upgrade pip && pip install virtualenv
RUN virtualenv /venv && . /venv/bin/activate && pip install --upgrade pip && pip install zappa

RUN mkdir /app
WORKDIR /app
