"""add user_social

Revision ID: 5ee8af1713e6
Revises: 783335ee2a08
Create Date: 2018-12-30 07:17:54.116550

"""
from alembic import op
import sqlalchemy as sa
import app.common.db


# revision identifiers, used by Alembic.
revision = '5ee8af1713e6'
down_revision = '783335ee2a08'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_social',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('social_provider', sa.String(length=80), nullable=True),
    sa.Column('social_id', sa.String(length=80), nullable=True),
    sa.Column('create_time', app.common.db.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('update_time', app.common.db.DateTimeUTC(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('social_id'),
    sa.UniqueConstraint('social_provider')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_social')
    # ### end Alembic commands ###
