"""make name nullable

Revision ID: 783335ee2a08
Revises: f6ab2cedc002
Create Date: 2018-12-16 09:23:45.683437

"""
from alembic import op
import sqlalchemy as sa
import app.common.db
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '783335ee2a08'
down_revision = 'f6ab2cedc002'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    # ### end Alembic commands ###
