"""create user

Revision ID: 8718fe3a46f1
Revises: 
Create Date: 2018-12-13 15:15:51.371686

"""
from alembic import op
import sqlalchemy as sa
import app.common.db


# revision identifiers, used by Alembic.
revision = '8718fe3a46f1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('lastfm_name', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('create_time', app.common.db.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('update_time', app.common.db.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('lastfm_name'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
