"""apply enum to social_provider

Revision ID: a7236217a140
Revises: 5ee8af1713e6
Create Date: 2019-01-04 14:35:29.056331

"""
from alembic import op
import sqlalchemy as sa
import app.common.db
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7236217a140'
down_revision = '5ee8af1713e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=True)
    op.add_column('user_social', sa.Column('provider', sa.Enum('FACEBOOK', name='socialprovider'), nullable=False))
    op.alter_column('user_social', 'social_id',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.drop_index('social_provider', table_name='user_social')
    op.drop_column('user_social', 'social_provider')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_social', sa.Column('social_provider', mysql.VARCHAR(length=80), nullable=True))
    op.create_index('social_provider', 'user_social', ['social_provider'], unique=True)
    op.alter_column('user_social', 'social_id',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    op.drop_column('user_social', 'provider')
    op.alter_column('user', 'email',
               existing_type=mysql.VARCHAR(length=120),
               nullable=False)
    # ### end Alembic commands ###
