"""add password to user

Revision ID: f6ab2cedc002
Revises: 8718fe3a46f1
Create Date: 2018-12-16 05:07:03.721907

"""
from alembic import op
import sqlalchemy as sa
import app.common.db
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f6ab2cedc002'
down_revision = '8718fe3a46f1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('password', sa.String(length=100), nullable=True))
    op.alter_column('user', 'lastfm_name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'lastfm_name',
               existing_type=mysql.VARCHAR(length=80),
               nullable=False)
    op.drop_column('user', 'password')
    # ### end Alembic commands ###
